services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8013:8000"
    volumes:
      - .:/app
      - ./downloads:/app/downloads # Mount the downloads directory
    env_file:
      - .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"